steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/frontend",
        "-f", "frontend/Dockerfile",
        "frontend",
        "--build-arg", "VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY",
        "--build-arg", "VITE_API_BASE_URL=$_VITE_API_BASE_URL",
        "--build-arg", "VITE_API_BASE_URL_IMAGE=$_VITE_API_BASE_URL_IMAGE"
      ]
images:
  - "gcr.io/$PROJECT_ID/frontend"
substitutions:
  _VITE_GOOGLE_MAPS_API_KEY: "PUT_YOUR_KEY_HERE"
  _VITE_API_BASE_URL: "/api"
  _VITE_API_BASE_URL_IMAGE: "https://YOUR_BACKEND_URL"
