steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/frontend",
        "-f", "frontend/Dockerfile",
        "frontend",
        "--build-arg", "VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY",
        "--build-arg", "VITE_API_BASE_URL=$_VITE_API_BASE_URL",
        "--build-arg", "VITE_API_BASE_URL_IMAGE=$_VITE_API_BASE_URL_IMAGE"
      ]
images:
  - "gcr.io/$PROJECT_ID/frontend"
substitutions:
  _VITE_GOOGLE_MAPS_API_KEY: "AIzaSyB7JcfJ0D3qepMYrKewniftNUjW3RnisHw"
  _VITE_API_BASE_URL: "https://cementeryo-128257388449.europe-west1.run.app/api"
  _VITE_API_BASE_URL_IMAGE: "https://cementeryo-128257388449.europe-west1.run.app/"
